export default theme = {
  font: "normal 11px Roboto, Tahoma, Arial, sans-serif",
  valueFont: "normal 700 11px/11px Roboto, Tahoma, Arial, sans-serif",
  timeFont: "normal 700 11px/11px Roboto, Tahoma, Arial, sans-serif",
  ordersAndPositionsFont: "10px normal Roboto, Tahoma, Arial, sans-serif",
  legendLabelColor: "#ffffff",
  legendLabelFont: "normal 300 11px/11px Roboto, Tahoma, Arial, sans-serif",
  legendValueFont: "normal 300 11px/11px Roboto, Tahoma, Arial, sans-serif",

  handlerColor: "handlerColor",
  timeAxisBackground: "timeAxisBackground",
  priceAxisBackground: "priceAxisBackground",
  backgroundColor: "componentBackground",
  gridColor: "gridColor",
  priceAxisTextColor: "priceAxisTextColor",
  timeAxisTextColor: "timeAxisTextColor",
  gridLineStyle: "",
  gridLineWidth: "",
  handlerSize: "8px",

  zeroLineColor: "",
  zeroLineStyle: "",
  zeroLineWidth: "",
  priceLineColor: "",
  priceLineStyle: "",
  priceLineWidth: "",
  priceLabelColor: "",
  priceLabelTextColor: "",

  defaultChartStyle: "",
  lineChartColor: "",
  lineChartLineStyle: "",
  lineChartLineWidth: "",
  histogramChartColor: "",
  histogramChartBarWidth: "",
  lineAndHistogramChartColor: "",
  lineAndHistogramLineStyle: "",
  lineAndHistogramLineWidth: "",
  lineAndHistogramBarWidth: "",
  barChart: "........",
  candlesChart: "........",

  defaultToolColor: "",
  defaultToolLineStyle: "",
  defaultToolLineWidth: "",
  defaultToolTextColor: "",
  defaultToolTextSize: "",
};
