function createUiTheme(config) {
  return {
    border: {
      inner: `1px solid ${config.divider}`,
      outter: `1px solid ${config.divider}`,
      radius: config.radius ?? 20,
    },
    gap: 10,
    accentColor: config.accent,
    buttons: {
      color: config.text,
      activeColor: config.text,
      activeBackground: config.controlActive,
      hoverColor: config.text,
      hoverBackground: config.control,
    },
    radioButton: {
      background: config.control,
      buttons: {
        color: config.mutedText,
        activeColor: config.text,
        hoverColor: config.text,
        hoverBackground: config.control,
      },
    },
    toolbar: {
      background: config.toolbarBackground,
      buttons: {
        color: config.mutedText,
        activeColor: config.text,
        activeBackground: config.controlActive,
        hoverColor: config.text,
        hoverBackground: config.control,
      },
      showCurrency: false,
      showShareChartButton: false,
      showChartScaleSwitch: false,
      topMenuPosition: "right",
    },
    subMenu: {
      background: config.panelStrong,
      buttons: {
        color: config.text,
        activeColor: config.text,
        activeBackground: config.controlActive,
        hoverColor: config.text,
        hoverBackground: config.control,
      },
    },
    splitButton: {
      openBackground: config.panelStrong,
      hoverBackground: config.panelStrong,
      openColor: config.text,
      hoverColor: config.text,
      arrowHoverBackground: config.control,
      arrowColor: config.arrow,
      arrowOpenColor: config.arrow,
    },
    dialog: {
      backgroundColor: config.panel,
      titleColor: config.text,
      textColor: config.text,
      dividerColor: config.divider,
      itemTitleColor: config.text,
      itemSubTitleColor: config.mutedText,
      itemHoverBackgroundColor: config.control,
    },
    inputs: {
      backgroundColor: config.panelStrong,
      placeholderColor: config.mutedText,
      textColor: config.text,
      labelColor: config.text,
    },
    scrollBar: {
      trackColor: "rgba(255, 255, 255, 0.04)",
      thumbColor: config.divider,
      thumbHoverColor: config.accent,
    },
  };
}

const signalChartTheme = {
  colors: {
    accent: { light: "#1e6cab", dark: "#13f899" },
    primaryTextColor: { light: "rgba(0, 0, 0, 0.87)", dark: "#ffffff" },
    disabledTextColor: { light: "rgba(0, 0, 0, 0.38)", dark: "rgba(255, 255, 255, 0.5)" },
    handlerColor: { light: "#c2c2c2", dark: "rgba(255, 255, 255, 0.1)" },
    iconColor: { light: "#000000", dark: "#ffffff" },
    backgroundColor: { light: "#f1f1f1", dark: "#100C22" },
    timeAxisBackground: { light: "#f1f1f1", dark: "#100C22" },
    priceAxisBackground: { light: "#f1f1f1", dark: "#100C22" },
    timeAxisTextColor: { light: "rgba(0, 0, 0, 0.54)", dark: "#6D86B1" },
    priceAxisTextColor: { light: "rgba(0, 0, 0, 0.54)", dark: "#6D86B1" },
    gridColor: { light: "#e0e0e0", dark: "#15132B" },
    chartZeroColor: { light: "#dd7423", dark: "#ffff00" },
    chartRed: { light: "#e53c42", dark: "#FF007B", bw: "#000000" },
    chartGreen: { light: "#00b05d", dark: "#17F7AB", bw: "#ffffff" },
    chartGreenBackground: { light: "#21CA83", dark: "#21CA83", bw: "#ffffff" },
    chartGray: { light: "#666666", dark: "#757578" },
    chartGrayPrimary: { light: "#666", dark: "#adadad" },
    chartRedStroke: { light: "#800000", dark: "#CB026B", bw: "#000000" },
    chartGreenStroke: { light: "#134d2c", dark: "#24C687", bw: "#000000" },
    chartFill: { light: "rgba(0, 0, 0, 0.06)", dark: "rgba(45,86,109,.3)" },
    chartStroke: { light: "#666", dark: "#2d566d" },
    buyColor: { light: "#00b05d", dark: "#229021" },
    sellColor: { light: "#e53c42", dark: "#FF007B" },
    exitAllColor: { light: "#666666", dark: "#aaaaaa" },
    defaultToolColor: { light: "#465054", dark: "#fafafa" },
    defaultToolTextColor: { light: "#ffffff", dark: "#001122" },
    crosshairColor: { light: "#465054", dark: "#13f899" },
    crosshairTextColor: { light: "#ffffff", dark: "#080821" },
    crosshairInnerColor: { light: "#465054", dark: "#080821" },
    crosshairInnerTextColor: { light: "#465054", dark: "#ffffff" },
    tipBackground: { light: "#666", dark: "#201E3E" },
    tipTextColor: { light: "#ffffff", dark: "#e3e3e3" },
    tipUnderline: { light: "rgba(255, 255, 255, 0.12)", dark: "rgba(255, 255, 255, 0.12)" },
    indicatorMarker: { light: "#1e6cab", dark: "#1f2029" },
    hitColor: { light: "rgba(0, 0, 0, 0.54)", dark: "rgba(255, 255, 255, 0.7)" },
    darkTextColor: { light: "rgba(0, 0, 0, 0.87)", dark: "rgba(0, 0, 0, 0.87)" },
    overlay: { light: "#e0e0e0", dark: "#1f2029" },
    legendLabelColor: { light: "#888792", dark: "#888792" },
    legendValueColor: { light: "#ffffff", dark: "#ffffff" },
    legendLineBackground: { light: "rgba(0, 0, 0, 0.1)", dark: "rgba(18, 15, 41, 0.6)" },
    fibonacciRetracementLine: { light: "rgba(0, 0, 0, 0.06)", dark: "rgba(255, 255, 255, 0.12)" },
  },
  fonts: {
    title: {
      light: 'bold 12px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      dark: 'bold 12px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    },
    text: {
      light: '11px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      dark: '11px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    },
    price: {
      light: '600 12px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      dark: '600 12px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    },
    priceSubscript: {
      light: 'bold 10px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      dark: 'bold 10px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    },
    time: {
      light: 'bold 11px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      dark: 'bold 11px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    },
    legend: {
      light: '12px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      dark: '12px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    },
    legendSubscript: {
      light: '10px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      dark: '10px Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    },
    fontName: { light: "Inter", dark: "Inter" },
  },
};

const exeriaChartTheme = {
  colors: {
    accent: { light: "#1e6cab", dark: "#2196f3" },
    primaryTextColor: { light: "rgba(0, 0, 0, 0.87)", dark: "#ffffff" },
    disabledTextColor: { light: "rgba(0, 0, 0, 0.38)", dark: "rgba(255, 255, 255, 0.5)" },
    handlerColor: { light: "#c2c2c2", dark: "#1c1d25" },
    iconColor: { light: "#000000", dark: "#ffffff" },
    backgroundColor: { light: "#f1f1f1", dark: "#282b38" },
    timeAxisBackground: { light: "#f1f1f1", dark: "#282b38" },
    priceAxisBackground: { light: "#f1f1f1", dark: "#282b38" },
    timeAxisTextColor: { light: "rgba(0, 0, 0, 0.54)", dark: "#2196f3" },
    priceAxisTextColor: { light: "rgba(0, 0, 0, 0.54)", dark: "#ffffff" },
    gridColor: { light: "#e0e0e0", dark: "#353741" },
    chartZeroColor: { light: "#dd7423", dark: "#ffff00" },
    chartRed: { light: "#e53c42", dark: "#e51c23", bw: "#000000" },
    chartGreen: { light: "#00b05d", dark: "#259b24", bw: "#ffffff" },
    chartGreenBackground: { light: "#21CA83", dark: "#229021", bw: "#ffffff" },
    chartGray: { light: "#666666", dark: "#757578" },
    chartGrayPrimary: { light: "#666", dark: "#adadad" },
    chartRedStroke: { light: "#800000", dark: "#ea494f", bw: "#000000" },
    chartGreenStroke: { light: "#134d2c", dark: "#51af50", bw: "#000000" },
    chartFill: { light: "rgba(0, 0, 0, 0.06)", dark: "rgba(45,86,109,.3)" },
    chartStroke: { light: "#666", dark: "#2d566d" },
    buyColor: { light: "#00b05d", dark: "#229021" },
    sellColor: { light: "#e53c42", dark: "#e11920" },
    exitAllColor: { light: "#666666", dark: "#aaaaaa" },
    defaultToolColor: { light: "#465054", dark: "#fafafa" },
    defaultToolTextColor: { light: "#ffffff", dark: "#001122" },
    crosshairColor: { light: "#465054", dark: "#2196f3" },
    crosshairTextColor: { light: "#ffffff", dark: "#ffffff" },
    crosshairInnerColor: { light: "#465054", dark: "#246197" },
    crosshairInnerTextColor: { light: "#465054", dark: "#ffffff" },
    tipBackground: { light: "#666", dark: "#1f2029" },
    tipTextColor: { light: "#ffffff", dark: "#e3e3e3" },
    tipUnderline: { light: "rgba(255, 255, 255, 0.12)", dark: "#282b38" },
    indicatorMarker: { light: "#1e6cab", dark: "#1f2029" },
    hitColor: { light: "rgba(0, 0, 0, 0.54)", dark: "rgba(255, 255, 255, 0.7)" },
    darkTextColor: { light: "rgba(0, 0, 0, 0.87)", dark: "rgba(0, 0, 0, 0.87)" },
    overlay: { light: "#e0e0e0", dark: "#1f2029" },
    legendLabelColor: { light: "rgba(0, 0, 0, 0.5)", dark: "rgba(255, 255, 255, 0.5)" },
    legendValueColor: { light: "#ffffff", dark: "#ffffff" },
    legendLineBackground: { light: "rgba(0, 0, 0, 0.1)", dark: "rgba(0, 0, 0, 0.1)" },
    fibonacciRetracementLine: { light: "rgba(0, 0, 0, 0.06)", dark: "rgba(255, 255, 255, 0.12)" },
  },
  fonts: {
    title: {
      light: "bold 12px Roboto, Tahoma, Arial, sans-serif",
      dark: "bold 12px Roboto, Tahoma, Arial, sans-serif",
    },
    text: {
      light: "11px Roboto, Tahoma, Arial, sans-serif",
      dark: "11px Roboto, Tahoma, Arial, sans-serif",
    },
    price: {
      light: "bold 11px Roboto, Tahoma, Arial, sans-serif",
      dark: "bold 11px Roboto, Tahoma, Arial, sans-serif",
    },
    priceSubscript: {
      light: "bold 10px Roboto, Tahoma, Arial, sans-serif",
      dark: "bold 10px Roboto, Tahoma, Arial, sans-serif",
    },
    time: {
      light: "bold 11px Roboto, Tahoma, Arial, sans-serif",
      dark: "bold 11px Roboto, Tahoma, Arial, sans-serif",
    },
    legend: {
      light: "11px Roboto, Tahoma, Arial, sans-serif",
      dark: "11px Roboto, Tahoma, Arial, sans-serif",
    },
    legendSubscript: {
      light: "9px Roboto, Tahoma, Arial, sans-serif",
      dark: "9px Roboto, Tahoma, Arial, sans-serif",
    },
    fontName: { light: "Roboto", dark: "Roboto" },
  },
};

const swipperChartTheme = {
  colors: {
    accent: { dark: "#1EA1CD" },
    primaryTextColor: { dark: "#fff" },
    disabledTextColor: { dark: "rgba(255, 255, 255, 0.5)" },
    iconColor: { dark: "#21C1F2" },
    backgroundColor: { dark: "transparent" },
    handlerColor: { dark: "rgba(255,255,255,0.1)" },
    timeAxisBackground: { dark: "transparent" },
    priceAxisBackground: { dark: "transparent" },
    timeAxisTextColor: { dark: "#1EA1CD" },
    priceAxisTextColor: { dark: "#1EA1CD" },
    gridColor: { dark: "rgba(255,255,255,0.1)" },
    chartZeroColor: { dark: "#21C1F2" },
    chartRed: { dark: "#ce3e5b" },
    chartGreen: { dark: "#3CC3AF" },
    chartGreenBackground: { dark: "#1f9e8b" },
    chartGray: { dark: "#1EA1CD" },
    chartGrayPrimary: { dark: "#1EA1CD" },
    chartRedStroke: { dark: "#af1d57" },
    chartGreenStroke: { dark: "#25AD98" },
    chartFill: { dark: "#21C1F2" },
    chartStroke: { dark: "#21C1F2" },
    buyColor: { dark: "#3CC3AF" },
    sellColor: { dark: "#ce3e5b" },
    exitAllColor: { dark: "#ce3e5b" },
    defaultToolColor: { dark: "#1EA1CD" },
    defaultToolTextColor: { dark: "#1EA1CD" },
    crosshairColor: { dark: "#21C1F2" },
    crosshairTextColor: { dark: "#fff" },
    crosshairInnerColor: { dark: "#1EA1CD" },
    crosshairInnerTextColor: { dark: "#fff" },
    tipBackground: { dark: "#1EA1CD" },
    tipTextColor: { dark: "rgba(255, 255, 255, 0.8)" },
    tipUnderline: { dark: "rgba(255, 255, 255, 0.1)" },
    indicatorMarker: { dark: "yellow" },
    hitColor: { dark: "rgba(255, 255, 255, 0.7)" },
    darkTextColor: { dark: "#fff" },
    overlay: { dark: "#ce3e5b" },
    legendLabelColor: { dark: "rgba(255,255,255,0.7)" },
    legendValueColor: { dark: "#fff" },
    legendLineBackground: { dark: "rgba(10, 39, 56, 0.7)" },
    fibonacciRetracementLine: { dark: "rgba(255, 255, 255, 0.1)" },
  },
  fonts: {
    title: { dark: "300 12px Chivo, Roboto, Tahoma, Arial, sans-serif" },
    text: { dark: "300 11px Chivo, Roboto, Tahoma, Arial, sans-serif" },
    price: { dark: "300 12px Chivo, Roboto, Tahoma, Arial, sans-serif" },
    priceSubscript: { dark: "300 10px Chivo, Roboto, Tahoma, Arial, sans-serif" },
    time: { dark: "300 11px Chivo, Roboto, Tahoma, Arial, sans-serif" },
    legend: { dark: "300 12px Chivo, Roboto, Tahoma, Arial, sans-serif" },
    legendSubscript: { dark: "300 10px Chivo, Roboto, Tahoma, Arial, sans-serif" },
    fontName: { dark: "Chivo" },
  },
};

const chartReviewThemes = {
  swipper: swipperChartTheme,
  signal: signalChartTheme,
  exeria: exeriaChartTheme,
};

const reviewUiThemes = {
  swipper: createUiTheme({
    accent: "#3CC3AF",
    arrow: "#21C1F2",
    toolbarBackground: "#113D59",
    panel: "#144869",
    panelStrong: "#1EA1CD",
    control: "rgba(255, 255, 255, 0.1)",
    controlActive: "#1EA1CD",
    text: "#ffffff",
    mutedText: "rgba(255, 255, 255, 0.76)",
    divider: "rgba(255, 255, 255, 0.12)",
  }),
  signal: createUiTheme({
    accent: "#13F899",
    arrow: "#13F899",
    toolbarBackground: "rgba(13, 11, 27, 0.95)",
    panel: "#181433",
    panelStrong: "#201E3E",
    control: "rgba(19, 248, 153, 0.1)",
    controlActive: "#163D3B",
    text: "#F5FFFD",
    mutedText: "#8FA6C9",
    divider: "rgba(109, 134, 177, 0.18)",
  }),
  exeria: createUiTheme({
    accent: "#2196F3",
    arrow: "#21C1F2",
    toolbarBackground: "#1f2029",
    panel: "#2f3444",
    panelStrong: "#246197",
    control: "rgba(33, 150, 243, 0.14)",
    controlActive: "#246197",
    text: "#ffffff",
    mutedText: "rgba(255, 255, 255, 0.74)",
    divider: "rgba(255, 255, 255, 0.12)",
  }),
};

export { chartReviewThemes, reviewUiThemes };
